package www.patient.jykj_zxyl.base.base_db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import www.patient.jykj_zxyl.base.base_db.entity.ArticleEntity;
import www.patient.jykj_zxyl.base.base_db.entity.PublishContentEntity;
import www.patient.jykj_zxyl.base.base_db.entity.StationEntity;
import www.patient.jykj_zxyl.base.base_db.entity.UploadFileEntity;

import www.patient.jykj_zxyl.base.base_db.dao.ArticleEntityDao;
import www.patient.jykj_zxyl.base.base_db.dao.PublishContentEntityDao;
import www.patient.jykj_zxyl.base.base_db.dao.StationEntityDao;
import www.patient.jykj_zxyl.base.base_db.dao.UploadFileEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleEntityDaoConfig;
    private final DaoConfig publishContentEntityDaoConfig;
    private final DaoConfig stationEntityDaoConfig;
    private final DaoConfig uploadFileEntityDaoConfig;

    private final ArticleEntityDao articleEntityDao;
    private final PublishContentEntityDao publishContentEntityDao;
    private final StationEntityDao stationEntityDao;
    private final UploadFileEntityDao uploadFileEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleEntityDaoConfig = daoConfigMap.get(ArticleEntityDao.class).clone();
        articleEntityDaoConfig.initIdentityScope(type);

        publishContentEntityDaoConfig = daoConfigMap.get(PublishContentEntityDao.class).clone();
        publishContentEntityDaoConfig.initIdentityScope(type);

        stationEntityDaoConfig = daoConfigMap.get(StationEntityDao.class).clone();
        stationEntityDaoConfig.initIdentityScope(type);

        uploadFileEntityDaoConfig = daoConfigMap.get(UploadFileEntityDao.class).clone();
        uploadFileEntityDaoConfig.initIdentityScope(type);

        articleEntityDao = new ArticleEntityDao(articleEntityDaoConfig, this);
        publishContentEntityDao = new PublishContentEntityDao(publishContentEntityDaoConfig, this);
        stationEntityDao = new StationEntityDao(stationEntityDaoConfig, this);
        uploadFileEntityDao = new UploadFileEntityDao(uploadFileEntityDaoConfig, this);

        registerDao(ArticleEntity.class, articleEntityDao);
        registerDao(PublishContentEntity.class, publishContentEntityDao);
        registerDao(StationEntity.class, stationEntityDao);
        registerDao(UploadFileEntity.class, uploadFileEntityDao);
    }
    
    public void clear() {
        articleEntityDaoConfig.clearIdentityScope();
        publishContentEntityDaoConfig.clearIdentityScope();
        stationEntityDaoConfig.clearIdentityScope();
        uploadFileEntityDaoConfig.clearIdentityScope();
    }

    public ArticleEntityDao getArticleEntityDao() {
        return articleEntityDao;
    }

    public PublishContentEntityDao getPublishContentEntityDao() {
        return publishContentEntityDao;
    }

    public StationEntityDao getStationEntityDao() {
        return stationEntityDao;
    }

    public UploadFileEntityDao getUploadFileEntityDao() {
        return uploadFileEntityDao;
    }

}
